Fix the testing strategy
preactjs-templates/default pull request #17
Opened 2018-05-01 16:54 UTC by zackkrida

Fixes the`test` npm script and moves the `tests` directory to the repo root, outside of the main `src` directory

2018-05-14 05:58 UTC, reznord commented
In `package.json`, you forgot to update the [`moduleNameMapper`](https://github.com/zackkrida/default/blob/d5def277e679136628cc5ef15540cc434b54c97d/template/package.json#L49) config here

2018-05-14 05:58 UTC, reznord requested changes

2018-05-14 05:58 UTC, reznord commented on template/package.json
>        "<rootDir>/src/tests/__mocks__/browserMocks.js"
this should be:

```
<rootDir>/tests/__mocks__/browserMocks.js
```

since we have moved tests out of the `src` folder

2018-05-14 10:50 UTC, reznord commented
and remove the `tests/` from the `src/`  folder

2018-05-25 14:02 UTC, zackkrida commented
@reznord yikes. my bad 😊

2018-09-06 09:19 UTC, reznord commented
This is solved in #20, closing this.

2018-09-06 09:19 UTC, closed without merging